#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source /opt/nyt/sbx/.nyt

export HOMEBREW_GITHUB_API_TOKEN=***REMOVED***

# include locally installed Cassandra in PATH
PATH="$PATH:$HOME/Applications/cassandra/bin"
