#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source /opt/nyt/sbx/.nyt

export HOMEBREW_GITHUB_API_TOKEN=c3a33aae81cc53746a0a89437bbf83975feb7174

# added by Anaconda2 2.5.0 installer
export PATH="/Users/207302/anaconda/bin:$PATH"

# include locally installed Cassandra in PATH
export PATH="$PATH:$HOME/Applications/cassandra/bin"

# include Datastax Opscenter for Apache Cassandra and Datastax Enterprise in PATH
export PATH="$PATH:$HOME/opscenter/bin"

export GOPATH="$HOME/Code/golang"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:/usr/local/go/bin"

# enable iTerm shell integration
source ~/.iterm2_shell_integration.`basename $SHELL`

# Add Google App Engine SDK for Java to PATH
export PATH="$PATH:$HOME/Applications/appengine-java-sdk-1.9.38/bin"

# The next line updates PATH for the Google Cloud SDK.
source '/Users/207302/Applications/google-cloud-sdk/path.zsh.inc'

# The next line enables shell command completion for gcloud.
source '/Users/207302/Applications/google-cloud-sdk/completion.zsh.inc'

export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/"

# Add Maven to PATH
export PATH="$PATH:/Users/207302/Applications/apache-maven-3.3.9/bin"

# Use neovim
alias vim="nvim"
